apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysite
    app.kubernetes.io/managed-by: Helm
  name: mysite
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: myapp
  type: NodePort
status:
  loadBalancer: {}
